# Generated by Django 4.0.2 on 2022-03-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
